"""extend youtube.video

Revision ID: 2444db5152e1
Revises: 928d4d384099
Create Date: 2021-02-27 06:47:24.913576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2444db5152e1'
down_revision = '928d4d384099'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('embeddable', sa.Boolean(), nullable=True), schema='youtube')
    op.add_column('video', sa.Column('private', sa.Boolean(), nullable=True, comment='true if unable to access true youtube video id'), schema='youtube')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'private', schema='youtube')
    op.drop_column('video', 'embeddable', schema='youtube')
    # ### end Alembic commands ###
