"""init

Revision ID: c6b1983e3bc1
Revises: 
Create Date: 2021-02-23 23:31:09.570663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6b1983e3bc1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('yt8m_id', sa.Text(), nullable=True, comment='See: http://research.google.com/youtube8m/video_id_conversion.html'),
    sa.Column('youtube_video_id', sa.Text(), nullable=False, comment='Unique Youtube Video ID'),
    sa.Column('title', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('youtube_video_id'),
    sa.UniqueConstraint('yt8m_id'),
    schema='youtube'
    )
    op.create_table('yt8m_vertical',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='youtube'
    )
    op.create_table('video_mutable_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=True, comment='number of views of the video'),
    sa.Column('view_magnitude', sa.SmallInteger(), sa.Computed('CEIL(LOG(views))', ), nullable=True, comment="order of magnitude of the 'views' column"),
    sa.ForeignKeyConstraint(['video_id'], ['youtube.video.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id'),
    schema='youtube'
    )
    op.create_table('yt8m_vocabulary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False, comment='the index as defined by the vocabulary file'),
    sa.Column('knowledge_graph_id', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('wiki_url', sa.Text(), nullable=True),
    sa.Column('vertical_id_1', sa.Integer(), nullable=True),
    sa.Column('vertical_id_2', sa.Integer(), nullable=True),
    sa.Column('vertical_id_3', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vertical_id_1'], ['youtube.yt8m_vertical.id'], ),
    sa.ForeignKeyConstraint(['vertical_id_2'], ['youtube.yt8m_vertical.id'], ),
    sa.ForeignKeyConstraint(['vertical_id_3'], ['youtube.yt8m_vertical.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('index'),
    sa.UniqueConstraint('name'),
    schema='youtube'
    )
    op.create_table('video_yt8m_vocabulary_map',
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('yt8m_vocabulary_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['youtube.video.id'], ),
    sa.ForeignKeyConstraint(['yt8m_vocabulary_id'], ['youtube.yt8m_vocabulary.id'], ),
    sa.UniqueConstraint('video_id'),
    sa.UniqueConstraint('yt8m_vocabulary_id'),
    schema='youtube'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_yt8m_vocabulary_map', schema='youtube')
    op.drop_table('yt8m_vocabulary', schema='youtube')
    op.drop_table('video_mutable_metadata', schema='youtube')
    op.drop_table('yt8m_vertical', schema='youtube')
    op.drop_table('video', schema='youtube')
    # ### end Alembic commands ###
