"""Create youtube table

Revision ID: e5faffc0d6c4
Revises: 
Create Date: 2021-02-21 21:40:10.226152

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e5faffc0d6c4"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE SCHEMA IF NOT EXISTS youtube")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "video",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("youtube_video_id", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="youtube",
    )
    op.create_index(
        op.f("ix_youtube_video_id"), "video", ["id"], unique=False, schema="youtube"
    )
    op.create_index(
        op.f("ix_youtube_video_youtube_video_id"),
        "video",
        ["youtube_video_id"],
        unique=False,
        schema="youtube",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_youtube_video_youtube_video_id"), table_name="video", schema="youtube"
    )
    op.drop_index(op.f("ix_youtube_video_id"), table_name="video", schema="youtube")
    op.drop_table("video", schema="youtube")
    op.execute("DROP SCHEMA youtube")
    # ### end Alembic commands ###
