"""add last_updated to video metadata

Revision ID: f830888cb73e
Revises: 2444db5152e1
Create Date: 2021-02-27 08:10:10.616839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f830888cb73e'
down_revision = '2444db5152e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_mutable_metadata', sa.Column('last_updated', sa.DateTime(timezone=True), server_default='now()', nullable=True), schema='youtube')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_mutable_metadata', 'last_updated', schema='youtube')
    # ### end Alembic commands ###
